## Q1: Fun with arrays

**A.**  Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.


**B.** Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [1]:
#PART A:
import numpy as np

a = np.arange(1, 16).reshape(3, 5).T
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [2]:
b = a[1:5:2]
b

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [3]:
# Part B:
import numpy as np

r, c = 10, 11

array = np.ones((r, c), dtype = int)
array[1:-1, 1:-1] = 0

print(array)

[[1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1]]


## Q3: Are you faster than numpy? No

Numpy of course has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`. Check the runtime as well.

In [4]:
import time

def stdev(a):
    abar = np.mean(a)
    square = (a - abar)**2
    sum = np.sum(square)
    var = sum /len(a)
    
    return np.sqrt(var)

array = np.random.rand(1000000)

t0 = time.time()
my_res = stdev(array)
t1 = time.time()

t2 = time.time()
numpy_res = np.std(array)
t3 = time.time()

print(f"My result: {my_res}")
print("Time elapsed: {} s".format(t1-t0))

print(f"Numpy's result: {numpy_res}")
print("Time elapsed: {} s".format(t3-t2))

print(f"Difference in results: {my_res - numpy_res}")
print("Numpy is {} times faster than me :(".format((t1-t0)/(t3-t2)))

My result: 0.2888318193815036
Time elapsed: 0.004016876220703125 s
Numpy's result: 0.2888318193815036
Time elapsed: 0.005136013031005859 s
Difference in results: 0.0
Numpy is 0.7821000835577012 times faster than me :(
